# Generated by Django 5.1 on 2024-09-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_created=True)),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
                ('model_year', models.IntegerField(verbose_name='Ano do modelo')),
                ('factory_year', models.IntegerField(verbose_name='Ano de fabricação')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Carros',
            },
        ),
    ]
