# Generated by Django 5.1 on 2024-09-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'verbose_name': 'Carro'},
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
