# Generated by Django 5.1 on 2024-09-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_carmodel_options_alter_carmodel_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
