# Generated by Django 5.1 on 2024-09-03 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_carmodel_last_modified'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarModel',
            new_name='Car',
        ),
    ]
