# Generated by Django 5.1 on 2024-09-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_rename_carmodel_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='next_qualification',
            field=models.DateField(blank=True, default='2024-09-03', verbose_name='Próxima qualificação'),
            preserve_default=False,
        ),
    ]
