# Generated by Django 5.1 on 2024-09-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_next_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano do modelo'),
        ),
        migrations.AlterField(
            model_name='car',
            name='next_qualification',
            field=models.DateField(blank=True, null=True, verbose_name='Próxima qualificação'),
        ),
    ]
