# Generated by Django 5.1 on 2024-09-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_brand_alter_car_id_alter_car_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Marca'},
        ),
        migrations.AddField(
            model_name='car',
            name='last_qualification',
            field=models.DateField(blank=True, null=True, verbose_name='Última qualificação'),
        ),
    ]
