# Generated by Django 5.1 on 2024-09-04 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_brand_options_car_last_qualification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='last_qualification',
        ),
        migrations.RemoveField(
            model_name='car',
            name='next_qualification',
        ),
    ]
