# Generated by Django 5.1 on 2024-09-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_alter_car_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Imagem'),
        ),
        migrations.AddField(
            model_name='car',
            name='plate_numer',
            field=models.IntegerField(blank=True, max_length=1, null=True, verbose_name='Final da placa'),
        ),
    ]
