# Generated by Django 5.1 on 2024-09-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_car_photo_car_plate_numer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='plate_numer',
            field=models.IntegerField(blank=True, null=True, verbose_name='Final da placa'),
        ),
    ]
