# Generated by Django 5.1 on 2024-09-10 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_alter_brand_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='plate_numer',
            new_name='plate_number',
        ),
    ]
